name: Docker_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

jobs:
  docker_build_test:
    name: Docker build test
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build -t dreal4_test .
      - name: test
        run: docker run -t dreal4_test dreal "-v"

  docker_pull_test:
    name: Docker pull test
    runs-on: ubuntu-24.04
    steps:
      - name: pull
        run: docker pull dreal/dreal4
      - name: test
        run: docker run -t dreal/dreal4 dreal "-v"

  docker_build_test_amazonlinux:
    name: Docker build test (Amazon Linux)
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: docker build -t dreal4_test_amazonlinux -f Dockerfile.amazonlinux .
      - name: test
        run: docker run -t dreal4_test_amazonlinux dreal "-v"

  docker_pull_test_amazonlinux:
    name: Docker pull test (Amazon Linux)
    runs-on: ubuntu-24.04
    steps:
      - name: pull
        run: docker pull dreal/dreal4:amazonlinux
      - name: test
        run: docker run -t dreal/dreal4:amazonlinux dreal "-v"
