name: MacOS_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

env:
  HOMEBREW_NO_AUTO_UPDATE: "1"

jobs:
  sequoia_build_and_test:
    runs-on: macos-15-large
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --verbose_failures

  sequoia_ubsan:
    runs-on: macos-15-large
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --config ubsan \
            --test_tag_filters=-no_ubsan \
            --verbose_failures

  sequoia_asan:
    runs-on: macos-15-large
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --config asan \
            --test_tag_filters=-no_asan \
            --verbose_failures
