name: MacOS_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 7 * * *'

env:
  HOMEBREW_NO_AUTO_UPDATE: "1"

jobs:
  sonoma_build_and_test:
    runs-on: macos-14-large
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: remove-bazelisk
        run: if [[ -e /usr/local/bin/bazelisk ]]; then brew rm bazelisk; fi
      - name: setup
        run: |
          rm -f '/usr/local/bin/2to3'
          ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --verbose_failures

  sequoia_build_and_test:
    runs-on: macos-15-large
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: remove-bazelisk
        run: if [[ -e /usr/local/bin/bazelisk ]]; then brew rm bazelisk; fi
      - name: setup
        run: |
          rm -f '/usr/local/bin/2to3'
          ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --verbose_failures

  sonoma_ubsan:
    runs-on: macos-14-large
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: remove-bazelisk
        run: if [[ -e /usr/local/bin/bazelisk ]]; then brew rm bazelisk; fi
      - name: setup
        run: |
          rm -f '/usr/local/bin/2to3'
          ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --config ubsan \
            --test_tag_filters=-no_ubsan \
            --verbose_failures

  sonoma_asan:
    runs-on: macos-14-large
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: remove-bazelisk
        run: if [[ -e /usr/local/bin/bazelisk ]]; then brew rm bazelisk; fi
      - name: setup
        run: |
          rm -f '/usr/local/bin/2to3'
          ./setup/mac/install_prereqs.sh
      - name: build and test
        run: |
          bazel test //... \
            -c dbg \
            --test_output=errors \
            --config asan \
            --test_tag_filters=-no_asan \
            --verbose_failures
